name: News Bot

on:
  schedule:
    - cron: "0 22 * * *" # 8am AEST
  workflow_dispatch:

jobs:
  send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Execute News Bot (#ai)
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_AI }}
          NEWSDATAIO_API_KEY: ${{ secrets.NEWSDATAIO_API_KEY }}
          NODE_NO_WARNINGS: 1
        run: node --experimental-strip-types bots/bot-news-ai.ts
